//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreshApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dimdate
    {
        public long id { get; set; }
        public string day { get; set; }
        public string color { get; set; }
    }
}
