//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreshApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WSC2024Selection_Mobile_StephenEntities : DbContext
    {
        public WSC2024Selection_Mobile_StephenEntities()
            : base("name=WSC2024Selection_Mobile_StephenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dimdate> dimdates { get; set; }
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
