//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class route
    {
        public long id { get; set; }
        public long location1Id { get; set; }
        public long location2Id { get; set; }
        public decimal cost { get; set; }
        public int duration { get; set; }
    
        public virtual location location { get; set; }
        public virtual location location1 { get; set; }
    }
}
